# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8478cf67ffdb6249bc13de6524c0c6ce"
name = "stellarCheckout"
handle = "stellarcheckout"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "stellarcheckout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
